### ISSUE TITLE
Double click to "Translate" - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by BigBoss320** [Farcrada/Double-click-to-edit#8]
Hey! I have a problem, the message does not want to be edited. It is not compatible when the "Google Translate" plugin is activated. _(See the attached video)_
[DoubleClickTo- 'Translate'.zip](https://github.com/Farcrada/Double-click-to-edit/files/3637472/DoubleClickTo-.Translate.zip)

**Comment by Farcrada** [comment]
Thanks for the report, do you have the version and source of the translator for me?

Preliminary analysis suggests (heh, always wanted to use that) that the translator plug-in uses the same functionality my/this plugin uses. As a result, the commands double stack and result in a double execute. 

I am afraid this is going to be an either or case, until I find a better way to do this or until the plugin you use enables you to ignore your own messages (since I'd assume you'd know what your own messages say, or is that an odd assumption?).

**Comment by BigBoss320** [comment]
In my opinion, the problem comes from the menu. When you double click on the message, the second option (edit) is done automatically. However, it is google translate that takes the second place.
[DoubleClick.zip](https://github.com/Farcrada/Double-click-to-edit/files/3638381/DoubleClick.zip)


Name : GoogleTranslationOption
Version : 1.7.4
by : DevilBro
Source (code) : https://bit.ly/2kLE6oO
Website (gitHub) : https://bit.ly/2mon14w

**Comment by Farcrada** [comment]
Found it, fix uploading now!

**Comment by Farcrada** [comment]
Should now update when pressing: "Check for updates" 

Fixed in: https://github.com/Farcrada/Double-click-to-edit/commit/060d2a6b2e23590bbf24e313e6664e900ca4a30f
Pushed to live with: https://github.com/Farcrada/Double-click-to-edit/commit/0b188986bc11ac48a34db4655ae773af21bd2373
